# Jupyter Notebook w VS Code: skróty klawiaturowe, praca z komórkami i formatowanie Markdown

Przewodnik referencyjny po notebookach `.ipynb` w Visual Studio Code (rozszerzenie **Jupyter**, ms-toolsai.jupyter). Ten plik jest jednocześnie **żywym przykładem**: komórki Markdown pokazują zarówno składnię (w blokach kodu), jak i jej wynik (renderowany tekst), więc możesz od razu porównać.

**Oznaczenia w tabelach skrótów** (system: Windows/Linux; na macOS zwykle `Ctrl`→`Cmd`, `Alt`→`Option`):

| Znacznik | Znaczenie |
|---|---|
| ✅ | Skrót zweryfikowany w oficjalnej dokumentacji VS Code lub w domyślnych skrótach (`keybindings`) |
| ◻ | Standardowy skrót edytora VS Code (działa w komórce jak w zwykłym pliku) |
| ⚠ | Zależy od wersji, ustawień lub rozszerzenia: sprawdź w swoim VS Code |

> **Jak sprawdzić dowolny skrót w swojej wersji:** `Ctrl+K Ctrl+S` (Keyboard Shortcuts) → wpisz `notebook` albo nazwę polecenia. Ikona „Show Same Keybindings" i kolumna *When* pokazują, w jakim kontekście skrót działa. Skróty bywają zmieniane między wersjami VS Code.

**Spis treści**

1. Tryby pracy i uruchamianie komórek
2. Skróty klawiaturowe (tryb poleceń, tryb edycji, edytor, wyniki, wyszukiwanie)
3. Własne skróty (`keybindings.json`) i paleta poleceń
4. Funkcje notebooka w VS Code: Variables, Data Viewer, Outline, debugowanie, diff, eksport
5. Magiczne polecenia IPython i wygodne ustawienia wyświetlania
6. **Formatowanie Markdown w komórkach** (kompletny przewodnik z przykładami)
7. Markdown generowany z kodu (`display(Markdown(...))`, LaTeX, HTML)
8. Struktura dobrego notebooka i dobre praktyki
9. Ściągawki (top skróty, Markdown)

---

## 1. Tryby pracy i uruchamianie komórek

Komórka może być w trzech stanach (według oficjalnej dokumentacji VS Code):

| Stan | Wygląd | Co można robić |
|---|---|---|
| **Niezaznaczona** | brak paska po lewej | nic (kliknięcie ją zaznacza) |
| **Tryb poleceń** (*command mode*) | pełny pionowy pasek po lewej stronie komórki | skróty jednoklawiszowe na komórce: `A`, `B`, `M`, `Y`, `D D`, `Z`… |
| **Tryb edycji** (*edit mode*) | pasek + obramowanie edytora | pisanie kodu/tekstu |

- `Enter`: z trybu poleceń do trybu edycji ✅
- `Esc`: z trybu edycji do trybu poleceń ✅ (działa, gdy nie ma zaznaczenia tekstu ani wielu kursorów)
- Myszką: kliknij pasek po lewej stronie komórki (tryb poleceń) lub wnętrze edytora (tryb edycji).

> **Ważne:** skróty jednoklawiszowe (`A`, `B`, `M`, `Y`, `D D`, `Z`, `J`, `K`, `L`) działają **tylko w trybie poleceń**. Jeśli wpisujesz je w edytorze, po prostu wstawiają literę.

### 1.1. Uruchamianie komórek

| Skrót | Działanie | Gdzie |
|---|---|---|
| `Ctrl+Enter` | Uruchom komórkę, zostań w niej ✅ | oba tryby |
| `Shift+Enter` | Uruchom komórkę i **zaznacz następną** (na końcu notebooka tworzy nową) ✅ | oba tryby |
| `Alt+Enter` | Uruchom komórkę i **wstaw nową komórkę poniżej**, przejdź do niej ✅ | oba tryby |
| `Ctrl+Enter` / `Shift+Enter` na komórce Markdown | Renderuje tekst (wychodzi z edycji) ✅ | tryb edycji |
| Przycisk ▶ po lewej / paski narzędzi | Run, Run All, Run All Above, Run All Below, Run Cells in Section ✅ | mysz |

> Uwaga: strona dokumentacji VS Code opisuje `Shift+Enter` i `Alt+Enter` nieprecyzyjnie. W domyślnych skrótach `Shift+Enter` to `notebook.cell.executeAndSelectBelow` (zaznacza następną komórkę), a `Alt+Enter` to `notebook.cell.executeAndInsertBelow` (wstawia nową i przechodzi do niej). Zweryfikuj w Keyboard Shortcuts w swojej wersji.

**Uruchamianie wielu komórek** (pasek narzędzi nad notebookiem lub paleta poleceń `Ctrl+Shift+P`):

| Polecenie | Efekt |
|---|---|
| Run All | Wszystkie komórki od góry do dołu |
| Run All Above / Run All Below | Wszystkie powyżej / poniżej zaznaczonej |
| Run Cells in Section | Komórki pod nagłówkiem Markdown (dostępne w widoku **Outline** i w **Sticky Scroll**) ✅ |
| Restart (kernel) → Run All | Czysty start: sprawdza, czy notebook działa „od zera" (zawsze rób to przed commitem) |
| Interrupt | Przerywa wykonywanie długiej komórki |
| Clear All Outputs | Czyści wyniki wszystkich komórek (przed commitem do Gita) |

---

## 2. Skróty klawiaturowe

### 2.1. Tryb poleceń (komórka zaznaczona, kursor poza edytorem)

| Skrót | Działanie | |
|---|---|---|
| `Enter` | Wejdź w tryb edycji komórki | ✅ |
| `A` / `B` | Wstaw komórkę **nad** / **pod** zaznaczoną | ✅ |
| `M` / `Y` | Zmień typ komórki na **M**arkdown / kod (**Y**) | ✅ |
| `D D` (dwa razy `D`) | Usuń zaznaczone komórki | ✅ |
| `Z` | Cofnij ostatnią zmianę (także przypadkowo usuniętą komórkę) | ✅ |
| `J` / `K` lub `↓` / `↑` | Zaznacz komórkę poniżej / powyżej | ✅ |
| `Ctrl+Home` / `Ctrl+End` | Przejdź do pierwszej / ostatniej komórki | ✅ |
| `Alt+↑` / `Alt+↓` | Przesuń zaznaczone komórki w górę / w dół | ✅ |
| `Shift+Alt+↑` / `Shift+Alt+↓` | Skopiuj komórkę w górę / w dół | ✅ |
| `Ctrl+C` / `Ctrl+X` / `Ctrl+V` | Kopiuj / wytnij / wklej **komórki** (gdy zaznaczone są komórki, nie tekst) | ⚠ |
| `Ctrl+Shift+V` | Wklej skopiowaną komórkę **nad** zaznaczoną | ✅ |
| `Delete` | Usuń zaznaczone komórki | ✅ |
| `L` | Włącz/wyłącz numery linii w **tej** komórce | ✅ |
| `Shift+L` | Włącz/wyłącz numery linii w **całym** notebooku | ✅ |
| `Ctrl+K M` | Zmień język/typ komórki (menu: Code, Markdown, Raw, inne języki kernela) | ✅ |
| `Ctrl+/` | Zakomentuj/odkomentuj zaznaczone komórki | ✅ |
| `Alt+Delete` | Wyczyść wyniki zaznaczonej komórki | ✅ |
| `Ctrl+K T` | Zwiń/rozwiń **wynik** komórki | ✅ |
| `Ctrl+K Y` | Przełącz przewijanie długiego wyniku (scrolling) | ✅ |
| `Ctrl+K Ctrl+C` | Zwiń/rozwiń **kod** komórki (zostaje wynik) | ✅ |
| `←` / `→` lub `Ctrl+Shift+[` / `Ctrl+Shift+]` | Zwiń / rozwiń sekcję (nagłówek Markdown z jego komórkami) | ✅ |
| `Ctrl+L` | Wyśrodkuj zaznaczoną komórkę w widoku | ✅ |
| `Ctrl+↓` / `Ctrl+Shift+↑` | Wejdź w wynik komórki / wyjdź z wyniku | ✅ |
| `Ctrl+.` | Szybkie akcje po błędzie komórki | ✅ |
| `Shift+Alt+F` | Formatuj komórkę / notebook | ✅ |
| `Shift+klik` / `Ctrl+klik` na komórkach | Zaznacz zakres / dowolny zestaw komórek (operacje dotyczą wszystkich) | ✅ |
| `Shift+↓` / `Shift+↑` (lub `Shift+J` / `Shift+K`) | Rozszerz zaznaczenie komórek | ⚠ |

### 2.2. Tryb edycji (kursor w komórce)

| Skrót | Działanie | |
|---|---|---|
| `Esc` | Wyjdź do trybu poleceń | ✅ |
| `Ctrl+Enter` / `Shift+Enter` / `Alt+Enter` | Uruchom komórkę (zob. 1.1) | ✅ |
| `Ctrl+K Ctrl+Shift+\` | **Podziel komórkę** w miejscu kursora | ✅ |
| `Ctrl+Space` | Podpowiedzi IntelliSense | ◻ |
| `Ctrl+Shift+Space` | Podpowiedź parametrów funkcji | ◻ |
| `Tab` / `Shift+Tab` | Wcięcie / wycofanie wcięcia (lub przyjęcie podpowiedzi) | ◻ |
| `Ctrl+/` | Zakomentuj/odkomentuj linię | ◻ |
| `Alt+↑` / `Alt+↓` | Przesuń linię w górę / w dół | ◻ |
| `Shift+Alt+↑` / `Shift+Alt+↓` | Skopiuj linię w górę / w dół | ◻ |
| `Ctrl+Shift+K` | Usuń linię | ◻ |
| `Ctrl+D` | Zaznacz kolejne wystąpienie słowa (wielokrotne kursory; w notebooku wymaga ustawienia `notebook.multiCursor.enabled` dla zaznaczania między komórkami) | ✅ |
| `Ctrl+Shift+L` | Zaznacz wszystkie wystąpienia (w notebooku: wszystkie dopasowania wyszukiwania) | ✅ |
| `Alt+Klik` | Dodaj kursor | ◻ |
| `Ctrl+Alt+↑` / `Ctrl+Alt+↓` | Dodaj kursor wyżej / niżej (Windows: może kolidować ze skrótami sterownika karty graficznej) | ◻ |
| `F2` | Zmień nazwę symbolu (rename) we wszystkich użyciach | ◻ |
| `F12` / `Alt+F12` | Przejdź do definicji / podgląd definicji | ◻ |
| `Ctrl+K Ctrl+I` | Pokaż informację (hover) pod kursorem | ◻ |
| `Shift+Alt+F` | Formatuj komórkę (wymaga formatera, np. Black/Ruff) | ✅ |
| `PageUp` / `PageDown` | Przewiń kursor w obrębie komórki o stronę | ✅ |
| `Ctrl+Z` / `Ctrl+Y` | Cofnij / ponów edycję w komórce | ◻ |

### 2.3. Wyszukiwanie w notebooku

| Skrót | Działanie | |
|---|---|---|
| `Ctrl+F` | Wyszukaj w notebooku (po komórkach) | ✅ |
| `F3` / `Shift+F3` | Następne / poprzednie dopasowanie | ✅ |
| `Esc` | Zamknij panel wyszukiwania | ✅ |
| Ikona filtra (lejek) w panelu | Szukaj w: źródło Markdown, wyrenderowany Markdown, kod, **wyniki** komórek (domyślnie tylko wejścia) | ✅ |
| `Ctrl+H` | Zamień (find & replace) | ◻ |
| `Ctrl+Shift+F` | Szukaj we wszystkich plikach projektu (także w `.ipynb`) | ◻ |

### 2.4. Nawigacja i okna

| Skrót | Działanie | |
|---|---|---|
| `Ctrl+Shift+P` | Paleta poleceń (wszystkie polecenia notebooka) | ◻ |
| `Ctrl+P` | Szybkie otwieranie plików | ◻ |
| `Ctrl+Shift+O` | Przejdź do symbolu / nagłówka w pliku (w notebooku: lista symboli komórek) | ⚠ |
| `Ctrl+B` | Pokaż/ukryj panel boczny (Explorer → **Outline**) | ◻ |
| `Ctrl+J` | Pokaż/ukryj panel dolny (terminal, problemy) | ◻ |
| `Ctrl+\` | Podziel edytor (dwa notebooki obok siebie, np. porównanie) | ◻ |
| `Ctrl+K Ctrl+S` | Otwórz **Keyboard Shortcuts** | ◻ |
| `Ctrl+K Z` | Tryb Zen (bez rozpraszaczy) | ◻ |
| `Ctrl+S` | Zapisz notebook | ✅ |
| `Ctrl+Tab` | Przełączanie między otwartymi plikami | ◻ |

### 2.5. Okno Interactive (`.py` z komórkami `# %%`)

Alternatywa dla `.ipynb`: zwykły plik Pythona z komórkami wydzielonymi komentarzem `# %%`, uruchamiany w oknie **Interactive Window**. Lepszy do kontroli wersji (czyste różnice w Git), możliwy do uruchomienia także jako skrypt.

```python
# %% [markdown]
# # Tytuł sekcji (komórka Markdown w pliku .py)

# %%
import pandas as pd
df = pd.DataFrame({"a": [1, 2, 3]})
df
```

| Skrót / akcja | Działanie | |
|---|---|---|
| `Shift+Enter` w pliku `.py` | Uruchom komórkę `# %%` w oknie Interactive | ✅ |
| `Ctrl+Enter` | Uruchom komórkę/zaznaczenie (zależnie od ustawień) | ⚠ |
| Pole wejściowe okna Interactive: `Enter` / `Shift+Enter` | Domyślnie `Enter` wykonuje, `Shift+Enter` wstawia nową linię (ustawienie `interactiveWindow.executeWithShiftEnter` zamienia role) | ✅ |
| `Ctrl+Home` / `Ctrl+End` | Przewiń okno Interactive na górę / dół | ✅ |
| `↑` / `↓` w polu wejściowym | Historia poleceń | ✅ |
| Polecenie **Jupyter: Export Current Python File as Jupyter Notebook** | Zamiana `# %%` w `.ipynb` | ⚠ |

---

## 3. Własne skróty (`keybindings.json`) i paleta poleceń

### 3.1. Jak dodać własny skrót

1. `Ctrl+K Ctrl+S` → wyszukaj polecenie (np. `Notebook: Clear All Outputs`) → dwukrotne kliknięcie → wciśnij kombinację; **albo**
2. Paleta poleceń → **Preferences: Open Keyboard Shortcuts (JSON)** → edytuj `keybindings.json`.

Klauzula `when` ogranicza kontekst, żeby skrót nie kolidował z edycją tekstu. Najważniejsze konteksty notebooka (potwierdzone w domyślnych skrótach):

| Kontekst (`when`) | Znaczenie |
|---|---|
| `notebookEditorFocused` | Aktywny jest edytor notebooka |
| `notebookCellListFocused` | Fokus na liście komórek (tryb poleceń) |
| `!inputFocus` | Kursor **nie** jest w polu tekstowym (tryb poleceń) |
| `inputFocus && notebookEditorFocused` | Kursor w edytorze komórki (tryb edycji) |
| `notebookCellEditable`, `notebookEditable` | Komórka/notebook można edytować |
| `notebookCellHasOutputs` | Komórka ma wynik |
| `notebookCellType == 'markup'` / `'code'` | Typ komórki |
| `activeEditor == 'workbench.editor.interactive'` | Okno Interactive |

### 3.2. Przykłady (`keybindings.json`)

Identyfikatory poniżej występują w domyślnych skrótach VS Code (sprawdzone); skróty klawiszowe po lewej to **propozycje** (zmień na wolne w Twoim układzie):

```json
[
  // czyszczenie wyniku bieżącej komórki jednym klawiszem w trybie poleceń
  { "key": "ctrl+alt+c", "command": "notebook.cell.clearOutputs",
    "when": "notebookEditorFocused && !inputFocus" },

  // podział komórki w miejscu kursora (prostszy niż domyślny Ctrl+K Ctrl+Shift+\)
  { "key": "ctrl+alt+s", "command": "notebook.cell.split",
    "when": "editorTextFocus && notebookCellEditable && notebookEditable && notebookEditorFocused" },

  // zwijanie kodu komórki (zostaje wynik)
  { "key": "ctrl+alt+h", "command": "notebook.cell.collapseCellInput",
    "when": "notebookCellListFocused && !inputFocus && !notebookCellInputIsCollapsed" },

  // wykonaj i wstaw nową komórkę poniżej także jako Ctrl+Shift+Enter
  { "key": "ctrl+shift+enter", "command": "notebook.cell.executeAndInsertBelow",
    "when": "notebookEditorFocused" },

  // usunięcie domyślnego skrótu: prefiks "-" przed identyfikatorem polecenia
  { "key": "alt+enter", "command": "-notebook.cell.executeAndInsertBelow" }
]
```

> Zmień **skrót**, nie `command`. Komentarze `//` są dozwolone w `keybindings.json`. Przy konflikcie skrótów (np. z innym rozszerzeniem) zobaczysz je w Keyboard Shortcuts → kolumna *Source* i *When*; wygrywa ostatnio zdefiniowany, pasujący do kontekstu.

### 3.3. Polecenia z palety (`Ctrl+Shift+P`), które warto znać

Nazwy w interfejsie angielskim (przy polskim interfejsie wpisuj po angielsku nadal działa wyszukiwanie po identyfikatorze lub fragmencie):

| Polecenie | Do czego |
|---|---|
| **Create: New Jupyter Notebook** | Nowy notebook ✅ |
| **Notebook: Select Notebook Kernel** | Wybór kernela / środowiska / zdalnego serwera ✅ |
| **Python: Select Interpreter** | Wybór interpretera Pythona (venv/conda) ✅ |
| **Jupyter: Restart Kernel**, **Interrupt Kernel** | Restart / przerwanie kernela ⚠ |
| **Notebook: Run All** / **Notebook: Clear All Outputs** | Uruchom wszystko / wyczyść wyniki ⚠ |
| **Notebook: Toggle Line Numbers** | Numery linii (jak `Shift+L`) ⚠ |
| **Notebook: Join Selected Cells**, **Notebook: Split Cell** | Łączenie / dzielenie komórek ⚠ |
| **Notebook: Fold All Cells**, **Notebook: Unfold All Cells** | Zwijanie wszystkich sekcji ⚠ |
| **Jupyter: Export to HTML/PDF/Python Script** (lub `…` → Export na pasku) | Eksport notebooka ✅ |
| **Notebook: Focus In Output** | Fokus na wyniku komórki ⚠ |
| **View: Toggle Sticky Scroll** | Przypięte nagłówki sekcji u góry ⚠ |
| **Preferences: Open Settings (UI/JSON)** | Ustawienia (np. `notebook.*`, `jupyter.*`) ✅ |
| **Developer: Reload Window** | Przeładowanie okna, gdy kernel/rozszerzenie „zwiesi się" ⚠ |

---

## 4. Funkcje notebooka w VS Code

### 4.1. Wybór kernela i środowiska

- Przycisk **Select Kernel** (prawy górny róg) → **Python Environments** (venv, conda, globalne) lub **Existing Jupyter Server** (zdalny serwer z `?token=`) ✅.
- W środowisku musi być zainstalowany `ipykernel` (`pip install ipykernel`; do debugowania wymagany `ipykernel` ≥ 6) ✅.
- Zmienne środowiskowe ładowane są z pliku **`.env`** w projekcie ✅.
- Notebook uruchamia się w kontekście **zaufanego** obszaru roboczego (*Workspace Trust*); w trybie ograniczonym (Restricted Mode) komórki nie wykonują się, a bogate wyniki są ukryte ✅.

### 4.2. Variables i Data Viewer

- Po uruchomieniu kodu kliknij ikonę **Variables** na pasku notebooka: lista zmiennych sesji z typem i wartością; odświeża się automatycznie ✅.
- Dwuklik na wierszu (lub **Show variable in data viewer**) otwiera **Data Viewer**: sortowanie, filtrowanie, przeglądanie `DataFrame`, tablic NumPy itp. (obsługa Polars zależy od wersji rozszerzenia) ✅.
- Filtrowanie wierszy: wpisz tekst w polu nad kolumną (zawiera), prefiks `=` (dokładne dopasowanie), **wyrażenie regularne** (zaawansowane) ✅.
- Alternatywa: rozszerzenie **Data Wrangler** (profilowanie, jakość danych, transformacje z generowaniem kodu pandas) ✅.

### 4.3. Outline (spis treści), Sticky Scroll, zwijanie

- Panel **Explorer → Outline** pokazuje strukturę notebooka. Domyślnie tylko nagłówki Markdown; ustawienia: `notebook.outline.showCodeCells`, `notebook.outline.showCodeCellSymbols`, `notebook.outline.showMarkdownHeadersOnly` ✅.
- **Run Cells in Section** w Outline i Sticky Scroll uruchamia komórki pod danym nagłówkiem ✅.
- Dobre nagłówki Markdown (`##`, `###`) = nawigacja, zwijanie sekcji (`←`/`→` w trybie poleceń) i uruchamianie sekcji.

### 4.4. Debugowanie

| Tryb | Jak | Uwagi |
|---|---|---|
| **Run by Line** | Przycisk w pasku komórki; kolejne kliknięcia wykonują po jednej instrukcji ✅ | Prosty, bez punktów przerwania |
| **Debug Cell** | Punkty przerwania (klik w lewym marginesie) + przycisk **Debug Cell** obok Run ✅ | Pełny debugger: stos, zmienne, krokowanie, wejście do innych komórek/modułów; **nie używa `launch.json`**, konfigurację zmienia np. `jupyter.debugJustMyCode` ✅ |
| `%debug` w komórce po wyjątku | Magia IPython (post-mortem) | Wpisz w następnej komórce po błędzie |

### 4.5. Wyniki: zapis wykresów, przewijanie, limity

- Najedź na wynik → ikona **Save** zapisuje wykres (matplotlib, Altair) ✅.
- Długie wyniki: `Ctrl+K Y` (przewijanie) i `Ctrl+K T` (zwijanie); ustawienia `notebook.output.textLineLimit`, `notebook.output.scrolling` ⚠.
- Wyniki można czyścić per komórka (`Alt+Delete`) lub dla całości (**Clear All Outputs**).

### 4.6. Git, diff i eksport

- **Notebook diff**: bogaty edytor różnic (wejście, wyniki, metadane); w menu `…` wybierasz, które składniki porównywać ✅. Ustawienia: `notebook.diff.ignoreOutputs`, `notebook.diff.ignoreMetadata` ⚠.
- Czystsze historie Git: czyść wyniki przed commitem lub użyj `nbstripout` (hook gita) / `jupytext` (parowanie `.ipynb` z `.py`) ⚠.
- **Export** (`…` → Export): `.py`, `.html`, `.pdf` ✅ (PDF wymaga zainstalowanego TeX; wykresy wyłącznie w SVG mogą się nie wyświetlić w PDF; wtedy eksport do HTML i druk z przeglądarki) ✅.

### 4.7. Przydatne ustawienia (`settings.json`)

| Ustawienie | Efekt |
|---|---|
| `notebook.lineNumbers` (`"on"`/`"off"`) | Numery linii w komórkach |
| `notebook.cellToolbarLocation` | Gdzie jest pasek narzędzi komórki |
| `notebook.output.textLineLimit` | Ile linii tekstowego wyniku pokazać (reszta zwinięta) |
| `notebook.formatOnSave.enabled` | Formatuj komórki przy zapisie (wymaga formatera) |
| `notebook.codeActionsOnSave` | Akcje przy zapisie (np. porządkowanie importów) |
| `notebook.stickyScroll.enabled` | Przypięte nagłówki sekcji |
| `notebook.outline.showCodeCells` | Pokaż komórki kodu w Outline ✅ |
| `notebook.diff.ignoreOutputs` | Pomijaj wyniki w diffach |
| `jupyter.debugJustMyCode` | Debugowanie tylko własnego kodu ✅ |
| `files.autoSave` | Automatyczny zapis (np. `"afterDelay"`) |
| `interactiveWindow.executeWithShiftEnter` | Zamiana `Enter`/`Shift+Enter` w oknie Interactive ✅ |
| `notebook.multiCursor.enabled` | Wielokrotne kursory między komórkami (`Ctrl+D`) ✅ |

> Nazwy ustawień sprawdź w *Settings* (`Ctrl+,`) wpisując `notebook` lub `jupyter`; część jest dostępna zależnie od wersji VS Code.

### 4.8. Profil „Data Science"

**Profiles → Create Profile… → Data Science (template)** tworzy profil z wyselekcjonowanymi rozszerzeniami, ustawieniami i snippetami (szybkie przełączanie między projektami) ✅.

---

## 5. Magiczne polecenia IPython i wygodne ustawienia wyświetlania

Kernel IPython (`ipykernel`) udostępnia polecenia „magiczne": `%` działa na jedną linię, `%%` na całą komórkę (musi być pierwszą linią). Poniżej bezpieczne przykłady do uruchomienia.

| Magia | Działanie |
|---|---|
| `%timeit wyrażenie` | Czas wykonania (wiele powtórzeń, średnia ± odchylenie) |
| `%%timeit` | To samo dla całej komórki |
| `%%time` | Jednorazowy czas komórki (CPU i ściany) |
| `%who`, `%whos` | Lista zmiennych w sesji (nazwy / szczegóły) |
| `%load_ext autoreload` + `%autoreload 2` | Automatyczne przeładowanie modułów `.py` po zmianie pliku (bez restartu kernela) |
| `%matplotlib inline` / `%matplotlib widget` | Wykresy w notebooku statyczne / interaktywne (widget wymaga `ipympl`) |
| `%run skrypt.py` | Uruchom skrypt w bieżącej sesji |
| `%env NAZWA=wartość` | Ustaw/odczytaj zmienną środowiskową |
| `%pwd`, `%cd katalog`, `%ls` | Katalog roboczy |
| `!polecenie` | Polecenie powłoki, np. `!pip install pakiet` (lepiej: `%pip install pakiet` instaluje w środowisku kernela) |
| `%%writefile plik.py` | Zapisz zawartość komórki do pliku |
| `%%bash`, `%%sql` (z rozszerzeniem) | Komórka w innym języku |
| `%debug`, `%pdb on` | Debugowanie po wyjątku |
| `%history -n -l 20` | Ostatnie 20 poleceń z numerami |

In [11]:
# działające przykłady (bez instalacji pakietów)
%load_ext autoreload
%autoreload 2

import numpy as np
%timeit np.arange(1000).sum()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
13.2 μs ± 6.33 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [12]:
%%time
total = sum(i * i for i in range(1_000_000))
total

CPU times: total: 219 ms
Wall time: 615 ms

333332833333500000

In [13]:
%whos

Variable   Type         Data/Info
---------------------------------
HTML       type         <class 'IPython.core.display.HTML'>
Latex      type         <class 'IPython.core.display.Latex'>
Markdown   type         <class 'IPython.core.display.Markdown'>
Math       type         <class 'IPython.core.display.Math'>
best       str          Północ
cell       dict         n=4
df         DataFrame         region  przychod  ma<...>  Wschód       141   0.15
display    function     <function display at 0x000002742D044900>
json       module       <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
level      int          3
line       str          - Specyfikacje: CommonMar<...>eX supported functions”).
m          NoneType     None
mean       float        52.4
nb         dict         n=4
nb_path    str          c:\Users\pkawk\Downloads\<...>r_vscode_przewodnik.ipynb
np         module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os         module       <module 'os' (frozen)>
pd         module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
pl         module       <module 'polars' from 'C:<...>es\\polars\\__init__.py'>
re         module       <module 're' from 'C:\\Pr<...>0\\Lib\\re\\__init__.py'>
rng        Generator    Generator(PCG64)
slug       str          93-gdzie-szukać-dalej
std        float        7.1
styled     Styler       <pandas.io.formats.style.<...>ct at 0x0000027438025160>
time       module       <module 'time' (built-in)>
title      str          9.3. Gdzie szukać dalej
toc        list         n=61
toc_md     str          - [Jupyter Notebook w VS <...>](#93-gdzie-szukać-dalej)
total      int          333332833333500000
tqdm       type         <class 'tqdm.auto.tqdm'>

### Wygodne ustawienia wyświetlania (pandas / Polars / NumPy)

In [14]:
import pandas as pd, polars as pl, numpy as np

pd.set_option("display.max_columns", 50)         # pokaż więcej kolumn
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:,.2f}".format)
pd.set_option("display.width", 140)

pl.Config.set_tbl_rows(20)                       # Polars: liczba wierszy w tabeli
pl.Config.set_tbl_cols(20)
pl.Config.set_fmt_str_lengths(60)

np.set_printoptions(precision=3, suppress=True, linewidth=120)

df = pd.DataFrame({"a": [1234.5678, 2.5], "b": ["x", "y"]})
df                                               # ostatnie wyrażenie w komórce jest wyświetlane automatycznie

         a  b
0 1,234.57  x
1     2.50  y

---

## 6. Formatowanie Markdown w komórkach

Komórki Markdown (`M` w trybie poleceń lub wybór typu komórki) renderują się po `Ctrl+Enter` / `Shift+Enter`; **dwuklik** (lub `Enter`) wraca do edycji. VS Code używa renderera zgodnego z CommonMark z rozszerzeniami (tabele, przekreślenia, autolinki, wzory KaTeX). Różnice względem GitHuba, klasycznego Jupytera i JupyterLab opisuję przy elementach oznaczonych ⚠.

W każdej poniższej komórce widzisz **składnię** (blok kodu) i **wynik** (ten sam tekst wyrenderowany), więc od razu sprawdzisz, co działa w Twojej wersji.

### 6.1. Nagłówki (struktura i nawigacja)

Nagłówki tworzą **spis treści w Outline**, umożliwiają zwijanie sekcji (`←` w trybie poleceń), uruchamianie sekcji (*Run Cells in Section*) i przypinanie w Sticky Scroll.

| Składnia | Poziom | Zalecane użycie |
|---|---|---|
| `# Tytuł` | 1 | **Jeden** na notebook: tytuł |
| `## Sekcja` | 2 | Główne części (Dane, Analiza, Wnioski) |
| `### Podsekcja` | 3 | Kroki w sekcji |
| `#### Szczegół` | 4 | Rzadko; opisy wewnątrz podsekcji |
| `##### `, `###### ` | 5, 6 | Praktycznie nie używaj (nieczytelne) |
| `Tytuł` + linia `====` | 1 (styl Setext) | Alternatywny zapis poziomów 1 i 2 (`----` = poziom 2); rzadko używany |

Zasady dobrych nagłówków:
- spacja po `#` jest **obowiązkowa** (`#Tytuł` nie jest nagłówkiem),
- nie przeskakuj poziomów (`#` → `###`),
- numeruj sekcje ręcznie (`## 3. Czyszczenie danych`), jeśli chcesz stałych odwołań w tekście,
- pusta linia przed i po nagłówku.

Poniższy kod pokazuje wygląd poziomów bez dodawania ich do Outline (wynik trafia do komórki kodu, a nie do struktury dokumentu):

In [15]:
from IPython.display import Markdown, display

display(Markdown("# Nagłówek 1\n## Nagłówek 2\n### Nagłówek 3\n#### Nagłówek 4\n##### Nagłówek 5\n###### Nagłówek 6"))

# Nagłówek 1
## Nagłówek 2
### Nagłówek 3
#### Nagłówek 4
##### Nagłówek 5
###### Nagłówek 6

### 6.2. Formatowanie tekstu

Pogrubienie, kursywa, przekreślenie, kod w linii i znaki specjalne.

**Składnia:**

````markdown
**pogrubienie** lub __pogrubienie__  
*kursywa* lub _kursywa_  
***pogrubiona kursywa***  
~~przekreślenie~~  
`kod w linii` (np. `df.groupby("region")`)  
Indeks górny: x<sup>2</sup>, dolny: H<sub>2</sub>O  
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> (klawisze)  
<mark>zaznaczenie</mark> (może nie działać)  
Znaki specjalne wyłączamy ukośnikiem: \*to nie kursywa\*, 5 \* 3, \# nie nagłówek, \`nie kod\`
````

**Wynik:**

**pogrubienie** lub __pogrubienie__  
*kursywa* lub _kursywa_  
***pogrubiona kursywa***  
~~przekreślenie~~  
`kod w linii` (np. `df.groupby("region")`)  
Indeks górny: x<sup>2</sup>, dolny: H<sub>2</sub>O  
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> (klawisze)  
<mark>zaznaczenie</mark> (może nie działać)  
Znaki specjalne wyłączamy ukośnikiem: \*to nie kursywa\*, 5 \* 3, \# nie nagłówek, \`nie kod\`

> Pogrubienie w środku wyrazu: `kot**ek**` działa dla `**`, a dla `_` nie (w `_` granice wyrazu są ścisłe). Znaki, które trzeba poprzedzić `\`: `` \ ` * _ { } [ ] ( ) # + - . ! | ``.

### 6.3. Akapity i łamanie linii

Pojedynczy Enter **nie** tworzy nowej linii: tekst zostaje w jednym akapicie. Nowy akapit = pusta linia. Wymuszone złamanie linii: dwie spacje na końcu linii, ukośnik `\` lub `<br>`.

**Składnia:**

````markdown
Pierwsza linia (dwie spacje na końcu)  
Druga linia w tym samym akapicie.

Trzecia linia z ukośnikiem na końcu\
czwarta linia po złamaniu.

Linia z tagiem HTML<br>i jej ciąg dalszy.

Nowy akapit (pusta linia wyżej).
````

**Wynik:**

Pierwsza linia (dwie spacje na końcu)  
Druga linia w tym samym akapicie.

Trzecia linia z ukośnikiem na końcu\
czwarta linia po złamaniu.

Linia z tagiem HTML<br>i jej ciąg dalszy.

Nowy akapit (pusta linia wyżej).

> Edytory często usuwają końcowe spacje przy zapisie (ustawienie `files.trimTrailingWhitespace`). Wtedy bezpieczniejszy jest `<br>` lub ukośnik na końcu linii.

### 6.4. Listy

Punktowane (`-`, `*`, `+`), numerowane (`1.`), zagnieżdżone (wcięcie 2–4 spacje lub Tab) oraz listy zadań (⚠ zależnie od wersji VS Code i trybu renderowania).

**Składnia:**

````markdown
- punkt pierwszy
- punkt drugi
  - zagnieżdżony (wcięcie 2 spacje)
    - jeszcze głębiej
- punkt trzeci

1. krok pierwszy
2. krok drugi
   1. podkrok
   2. podkrok
3. krok trzeci

Numeracja nie musi być kolejna (renderer ponumeruje sam):

1. a
1. b
1. c

Lista zadań (GitHub: checkboxy):

- [x] zrobione
- [ ] do zrobienia

Punkt z kodem w środku:

- Uruchom komórkę:

  ```python
  print("Hello")
  ```

- Następny punkt
````

**Wynik:**

- punkt pierwszy
- punkt drugi
  - zagnieżdżony (wcięcie 2 spacje)
    - jeszcze głębiej
- punkt trzeci

1. krok pierwszy
2. krok drugi
   1. podkrok
   2. podkrok
3. krok trzeci

Numeracja nie musi być kolejna (renderer ponumeruje sam):

1. a
1. b
1. c

Lista zadań (GitHub: checkboxy):

- [x] zrobione
- [ ] do zrobienia

Punkt z kodem w środku:

- Uruchom komórkę:

  ```python
  print("Hello")
  ```

- Następny punkt

> Pusta linia **przed** listą jest zalecana. Treść kontynuacyjna (kod, akapit) w punkcie musi mieć wcięcie równe początkowi tekstu punktu.

### 6.5. Cytaty, uwagi i wyróżnione bloki

Cytat to linie zaczynające się od `>`. Notebooki nie mają natywnych „callout-ów”, więc używaj cytatów z pogrubioną etykietą (działa wszędzie). Składnia alertów GitHuba (`> [!NOTE]`) jest renderowana tylko tam, gdzie renderer ją obsługuje (⚠ sprawdź w swojej wersji).

**Składnia:**

````markdown
> Zwykły cytat. Może mieć kilka linii
> i **formatowanie**.
>
> > Cytat zagnieżdżony.

> **Uwaga:** wartości w kolumnie `revenue` są w tys. PLN.

> **Wskazówka:** użyj `df.info()` przed analizą.

> **Ostrzeżenie:** komórka modyfikuje dane w miejscu.

> [!NOTE]
> Alert w stylu GitHub (działa zależnie od renderera).
````

**Wynik:**

> Zwykły cytat. Może mieć kilka linii
> i **formatowanie**.
>
> > Cytat zagnieżdżony.

> **Uwaga:** wartości w kolumnie `revenue` są w tys. PLN.

> **Wskazówka:** użyj `df.info()` przed analizą.

> **Ostrzeżenie:** komórka modyfikuje dane w miejscu.

> [!NOTE]
> Alert w stylu GitHub (działa zależnie od renderera).

### 6.6. Kod w Markdown

Kod w linii: pojedyncze grawisy. Blok: trzy grawisy z nazwą języka (podświetlanie składni zależy od motywu i gramatyk zainstalowanych w VS Code). Gdy kod zawiera grawisy, użyj **czterech** grawisów jako ogrodzenia.

**Składnia:**

````markdown
Inline: `SELECT * FROM tabela`, wywołanie `pd.read_csv("plik.csv")`.

```python
import pandas as pd
df = pd.read_csv("dane.csv")
df.head()
```

```sql
SELECT region, SUM(revenue) AS total
FROM sales
GROUP BY region
ORDER BY total DESC;
```

```bash
pip install pandas polars
```

```json
{"nazwa": "test", "wartosc": 1}
```

```diff
- stara linia
+ nowa linia
```

Blok bez języka (tekst):

```
Zwykły tekst
bez podświetlania
```

Wcięcie 4 spacjami też tworzy blok kodu (styl klasyczny):

    x = 1
    y = 2
````

**Wynik:**

Inline: `SELECT * FROM tabela`, wywołanie `pd.read_csv("plik.csv")`.

```python
import pandas as pd
df = pd.read_csv("dane.csv")
df.head()
```

```sql
SELECT region, SUM(revenue) AS total
FROM sales
GROUP BY region
ORDER BY total DESC;
```

```bash
pip install pandas polars
```

```json
{"nazwa": "test", "wartosc": 1}
```

```diff
- stara linia
+ nowa linia
```

Blok bez języka (tekst):

```
Zwykły tekst
bez podświetlania
```

Wcięcie 4 spacjami też tworzy blok kodu (styl klasyczny):

    x = 1
    y = 2

> Nazwy języków: `python`, `sql`, `bash`/`sh`, `json`, `yaml`, `r`, `html`, `javascript`, `diff`, `text`. Kod w komórce Markdown **nie jest wykonywany**: tylko wyświetlany.

### 6.7. Linki

Zewnętrzne, względne (do plików w projekcie), w stylu referencyjnym, autolinki i odnośniki do nagłówków w tym samym notebooku (⚠ działanie zależy od wersji; zasada: nagłówek zamieniany na małe litery, spacje na `-`, znaki interpunkcyjne usuwane).

**Składnia:**

````markdown
[Dokumentacja VS Code](https://code.visualstudio.com/docs/datascience/jupyter-notebooks)  
[Link z podpowiedzią](https://www.python.org "Oficjalna strona Pythona")  
Autolink: <https://pandas.pydata.org>  
Adres e-mail: <adres@przyklad.pl>  
Link względny do pliku: [dane](data/dane.csv) lub [inny notebook](analiza/eda.ipynb)  
Odnośnik do nagłówka w tym notebooku: [przejdź do sekcji 6.9](#69-tabele)  
Styl referencyjny: [Pandas][pd] i [Polars][pl]

[pd]: https://pandas.pydata.org
[pl]: https://pola.rs
````

**Wynik:**

[Dokumentacja VS Code](https://code.visualstudio.com/docs/datascience/jupyter-notebooks)  
[Link z podpowiedzią](https://www.python.org "Oficjalna strona Pythona")  
Autolink: <https://pandas.pydata.org>  
Adres e-mail: <adres@przyklad.pl>  
Link względny do pliku: [dane](data/dane.csv) lub [inny notebook](analiza/eda.ipynb)  
Odnośnik do nagłówka w tym notebooku: [przejdź do sekcji 6.9](#69-tabele)  
Styl referencyjny: [Pandas][pd] i [Polars][pl]

[pd]: https://pandas.pydata.org
[pl]: https://pola.rs

> Link do konkretnej **komórki** nie istnieje; używaj nagłówków. Odnośniki do nagłówków tworzą się z tekstu nagłówka (np. `## 6.9. Tabele` → `#69-tabele`); jeśli nie działa, sprawdź zapis w podglądzie lub użyj ręcznej kotwicy HTML `<a id="tabele"></a>` i linku `[tabele](#tabele)` (⚠).

### 6.8. Obrazy

**Składnia:** `![tekst alternatywny](ścieżka_lub_URL "opcjonalny tytuł")`

| Sposób | Zapis | Uwagi |
|---|---|---|
| Plik lokalny (względna ścieżka) | `![wykres](img/wykres.png)` | Ścieżka względem pliku `.ipynb`; plik musi być w repozytorium, aby widział go ktoś inny |
| Adres URL | `![logo](https://przyklad.pl/logo.png)` | Wymaga internetu przy otwarciu |
| **Załącznik** (wklejony do komórki) | `![obraz](attachment:image.png)` | W VS Code wklej obraz (`Ctrl+V`) lub przeciągnij do komórki Markdown: zapisuje się **wewnątrz pliku `.ipynb`** (base64), więc notebook jest samodzielny, ale plik rośnie ⚠ |
| Rozmiar i wyrównanie | `<img src="img/wykres.png" width="400">` | Czysty Markdown nie ma rozmiaru obrazu; użyj tagu HTML |
| Wyśrodkowanie | `<p align="center"><img src="..." width="400"></p>` | ⚠ zależnie od renderera |
| Obraz z kodu | `from IPython.display import Image; Image("img/wykres.png", width=400)` | W komórce kodu |
| Wykres | `plt.show()` / `fig.show()` | Najlepsze dla wykresów: powstają z danych, są powtarzalne |

> Zasada: wykresy generuj **kodem**, a obrazy w Markdown rezerwuj dla schematów, zrzutów ekranu i logo.

### 6.9. Tabele

Nagłówek i wiersz separatora `---` są obowiązkowe. Wyrównanie kolumn: `:---` (lewo), `:---:` (środek), `---:` (prawo). Wewnątrz komórek działa formatowanie w linii, a znak `|` trzeba poprzedzić `\`.

**Składnia:**

````markdown
| Metryka | Wartość | Zmiana |
|:--------|--------:|:------:|
| **Przychód** | 1 250 000 | ▲ 4,2% |
| Marża | 18,5% | ▼ 0,3 pp |
| `churn` | 3,1% | ➖ |
| Warunek A \| B | tak | ✅ |

| Wiele linii w komórce |
|---|
| pierwsza<br>druga<br>trzecia |
````

**Wynik:**

| Metryka | Wartość | Zmiana |
|:--------|--------:|:------:|
| **Przychód** | 1 250 000 | ▲ 4,2% |
| Marża | 18,5% | ▼ 0,3 pp |
| `churn` | 3,1% | ➖ |
| Warunek A \| B | tak | ✅ |

| Wiele linii w komórce |
|---|
| pierwsza<br>druga<br>trzecia |

> Kolejne linie tabeli nie mogą być przedzielone pustą linią. Ładne wyrównanie w źródle jest opcjonalne. Tabelę z `DataFrame` wygenerujesz przez `df.to_markdown()` (pakiet `tabulate`) i `display(Markdown(...))` (zob. sekcja 7).

### 6.10. Matematyka (LaTeX / KaTeX)

Wzory w linii: `$...$`, wzory wyśrodkowane w osobnym bloku: `$$...$$`. VS Code renderuje je silnikiem **KaTeX** (obsługuje większość popularnych poleceń LaTeX; nie wszystkie pakiety). Wzory w tekście: stała $\pi \approx 3{,}14159$, średnia $\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i$.

**Składnia:**

````markdown
Inline: wartość oczekiwana $E[X] = \mu$ i wariancja $\mathrm{Var}(X) = \sigma^2$.

Blok:

$$
z = \frac{x - \mu}{\sigma}
$$

Kilka linii wyrównanych do znaku `=` (środowisko `aligned`):

$$
\begin{aligned}
\text{MSE} &= \frac{1}{n}\sum_{i=1}^{n}\left(y_i - \hat{y}_i\right)^2 \\
\text{RMSE} &= \sqrt{\text{MSE}} \\
R^2 &= 1 - \frac{\sum_i (y_i-\hat{y}_i)^2}{\sum_i (y_i-\bar{y})^2}
\end{aligned}
$$

Macierz i układ równań:

$$
\mathbf{X}\boldsymbol{\beta} = \mathbf{y}, \qquad
\mathbf{X} = \begin{bmatrix} 1 & x_{11} & x_{12} \\ 1 & x_{21} & x_{22} \end{bmatrix}, \qquad
\hat{\boldsymbol{\beta}} = (\mathbf{X}^\top \mathbf{X})^{-1}\mathbf{X}^\top\mathbf{y}
$$

Funkcja kawałkowa:

$$
\mathrm{ReLU}(x) = \begin{cases} x & x > 0 \\ 0 & x \le 0 \end{cases}
$$
````

**Wynik:**

Inline: wartość oczekiwana $E[X] = \mu$ i wariancja $\mathrm{Var}(X) = \sigma^2$.

Blok:

$$
z = \frac{x - \mu}{\sigma}
$$

Kilka linii wyrównanych do znaku `=` (środowisko `aligned`):

$$
\begin{aligned}
\text{MSE} &= \frac{1}{n}\sum_{i=1}^{n}\left(y_i - \hat{y}_i\right)^2 \\
\text{RMSE} &= \sqrt{\text{MSE}} \\
R^2 &= 1 - \frac{\sum_i (y_i-\hat{y}_i)^2}{\sum_i (y_i-\bar{y})^2}
\end{aligned}
$$

Macierz i układ równań:

$$
\mathbf{X}\boldsymbol{\beta} = \mathbf{y}, \qquad
\mathbf{X} = \begin{bmatrix} 1 & x_{11} & x_{12} \\ 1 & x_{21} & x_{22} \end{bmatrix}, \qquad
\hat{\boldsymbol{\beta}} = (\mathbf{X}^\top \mathbf{X})^{-1}\mathbf{X}^\top\mathbf{y}
$$

Funkcja kawałkowa:

$$
\mathrm{ReLU}(x) = \begin{cases} x & x > 0 \\ 0 & x \le 0 \end{cases}
$$

#### Kompendium LaTeX do analiz danych i ML

| Co | Zapis | Wynik |
|---|---|---|
| Ułamek | `\frac{a}{b}` | $\frac{a}{b}$ |
| Potęga, indeks | `x^{2}`, `x_{i}`, `x_i^2` | $x^{2}$, $x_{i}$, $x_i^2$ |
| Pierwiastek | `\sqrt{x}`, `\sqrt[3]{x}` | $\sqrt{x}$, $\sqrt[3]{x}$ |
| Suma, iloczyn | `\sum_{i=1}^{n}`, `\prod_{i=1}^{n}` | $\sum_{i=1}^{n}$, $\prod_{i=1}^{n}$ |
| Całka | `\int_a^b f(x)\,dx` | $\int_a^b f(x)\,dx$ |
| Granica | `\lim_{n \to \infty}` | $\lim_{n \to \infty}$ |
| Greckie | `\alpha \beta \gamma \mu \sigma \theta \lambda \epsilon \Delta \Sigma` | $\alpha\ \beta\ \gamma\ \mu\ \sigma\ \theta\ \lambda\ \epsilon\ \Delta\ \Sigma$ |
| Kapelusz, kreska, tylda | `\hat{y}`, `\bar{x}`, `\tilde{x}` | $\hat{y}$, $\bar{x}$, $\tilde{x}$ |
| Wektor, macierz (pogrubione) | `\mathbf{x}`, `\boldsymbol{\beta}` | $\mathbf{x}$, $\boldsymbol{\beta}$ |
| Transpozycja, odwrotność | `\mathbf{X}^\top`, `\mathbf{X}^{-1}` | $\mathbf{X}^\top$, $\mathbf{X}^{-1}$ |
| Relacje | `\le \ge \ne \approx \sim \propto` | $\le\ \ge\ \ne\ \approx\ \sim\ \propto$ |
| Strzałki | `\to \Rightarrow \leftarrow` | $\to\ \Rightarrow\ \leftarrow$ |
| Operatory | `\cdot \times \pm \mid \in \notin \subset` | $\cdot\ \times\ \pm\ \mid\ \in\ \notin\ \subset$ |
| Funkcje | `\log \ln \exp \sin \max \min \arg\max` | $\log\ \ln\ \exp\ \sin\ \max\ \min\ \arg\max$ |
| Tekst w formule | `\text{jeśli } x > 0` | $\text{jeśli } x > 0$ |
| Prawdopodobieństwo warunkowe | `P(A \mid B)` | $P(A \mid B)$ |
| Norma | `\lVert \mathbf{x} \rVert_2` | $\lVert \mathbf{x} \rVert_2$ |
| Wartość bezwzględna | `\lvert x \rvert` | $\lvert x \rvert$ |
| Nawiasy skalowane | `\left( \frac{a}{b} \right)` | $\left( \frac{a}{b} \right)$ |
| Odstępy | `\,` (mały), `\;` (średni), `\quad`, `\qquad` | $a\,b\;c\quad d$ |
| Kropki | `\ldots`, `\cdots` | $1, 2, \ldots, n$ |

**Wzory często używane w analizach i ML** (gotowe do skopiowania):

$$
\text{Odchylenie standardowe: } s = \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar{x})^2}
\qquad
\text{Korelacja: } r = \frac{\sum_i (x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum_i (x_i-\bar{x})^2}\sqrt{\sum_i (y_i-\bar{y})^2}}
$$

$$
\text{Min-max: } x' = \frac{x - x_{\min}}{x_{\max} - x_{\min}}
\qquad
\text{Standaryzacja: } z = \frac{x-\mu}{\sigma}
\qquad
\text{Odporna: } x' = \frac{x - \mathrm{med}(x)}{\mathrm{IQR}(x)}
$$

$$
\sigma(z) = \frac{1}{1+e^{-z}}
\qquad
\mathrm{softmax}(z_i) = \frac{e^{z_i}}{\sum_{j} e^{z_j}}
\qquad
\mathcal{L} = -\frac{1}{n}\sum_i \left[ y_i\log \hat{p}_i + (1-y_i)\log(1-\hat{p}_i) \right]
$$

$$
P(A \mid B) = \frac{P(B \mid A)\,P(A)}{P(B)}
\qquad
f(x) = \frac{1}{\sigma\sqrt{2\pi}}\exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)
$$

$$
\text{Precision} = \frac{TP}{TP+FP}, \quad
\text{Recall} = \frac{TP}{TP+FN}, \quad
F_1 = \frac{2\,\text{Precision}\cdot\text{Recall}}{\text{Precision}+\text{Recall}}
$$

> **Wskazówki:** w `$...$` nie zostawiaj spacji tuż po otwierającym i przed zamykającym `$` (`$ x $` w niektórych rendererach nie jest wzorem); do wielu linii używaj `aligned` (nie `align`), do tekstu `\text{}`; znak dolara w tekście zapisz jako `\$`. Przecinek dziesiętny w wzorze: `3{,}14` (bez nawiasów klamrowych LaTeX dodaje odstęp po przecinku). Jeśli wzór nie renderuje się w Twojej wersji, sprawdź, czy nie ma w nim polecenia spoza KaTeX.

### 6.11. HTML wewnątrz Markdown

Renderer VS Code zezwala na podzbiór HTML (zablokowane są m.in. skrypty). Dostępność atrybutów, szczególnie `style`, zależy od wersji i ustawień zabezpieczeń (⚠). Sprawdź w poniższym wyniku, które elementy działają u Ciebie.

**Składnia:**

````markdown
<details>
<summary>Kliknij, aby rozwinąć (sekcja zwijana)</summary>

Ukryta treść **z Markdownem**, listą:

- element 1
- element 2

</details>

Tekst z <span style="color: crimson">kolorem (style)</span> i <span style="background-color: #fff3cd">tłem</span>.

<div align="center"><b>Tekst wyśrodkowany (div align)</b></div>

<table>
  <tr><th>HTML</th><th>tabela</th></tr>
  <tr><td>komórka</td><td>scalona <br> w dwie linie</td></tr>
</table>

Poziom linii poniżej:

<hr>

<!-- Komentarz HTML: nie jest widoczny po renderowaniu -->
Tekst po komentarzu (komentarz jest w źródle, nie w wyniku).
````

**Wynik:**

<details>
<summary>Kliknij, aby rozwinąć (sekcja zwijana)</summary>

Ukryta treść **z Markdownem**, listą:

- element 1
- element 2

</details>

Tekst z <span style="color: crimson">kolorem (style)</span> i <span style="background-color: #fff3cd">tłem</span>.

<div align="center"><b>Tekst wyśrodkowany (div align)</b></div>

<table>
  <tr><th>HTML</th><th>tabela</th></tr>
  <tr><td>komórka</td><td>scalona <br> w dwie linie</td></tr>
</table>

Poziom linii poniżej:

<hr>

<!-- Komentarz HTML: nie jest widoczny po renderowaniu -->
Tekst po komentarzu (komentarz jest w źródle, nie w wyniku).

> Komentarze `<!-- ... -->` służą do notatek w źródle komórki. Dla kolorów i rozbudowanych układów bezpieczniej użyć **kodu** (`display(HTML(...))`, sekcja 7) niż HTML w komórce Markdown.

### 6.12. Linie poziome i separatory

Trzy lub więcej `-`, `*` lub `_` w osobnej linii (pusta linia przed `---` bezpośrednio pod tekstem, bo inaczej powstanie nagłówek Setext).

**Składnia:**

````markdown
Sekcja pierwsza

---

Sekcja druga

***

Sekcja trzecia
````

**Wynik:**

Sekcja pierwsza

---

Sekcja druga

***

Sekcja trzecia

### 6.13. Elementy zależne od rozszerzeń i wersji (⚠ sprawdź u siebie)

| Element | Składnia | Wymaga |
|---|---|---|
| **Diagramy Mermaid** | blok ` ```mermaid ` z kodem grafu (flowchart, sequenceDiagram, gantt) | Rozszerzenie typu „Markdown Preview Mermaid Support” (renderowanie w notebookach zależy od rozszerzenia i wersji VS Code); GitHub renderuje Mermaid natywnie |
| **Przypisy dolne** | `tekst[^1]` + `[^1]: treść przypisu` | Rozszerzenie dodające składnię przypisów (np. „Markdown Footnotes”) |
| **Emoji jako kody** | `:rocket:` | W VS Code zwykle nie; wklejaj emoji bezpośrednio (🚀) |
| **Alerty GitHub** | `> [!NOTE]`, `[!TIP]`, `[!WARNING]` | Renderer obsługujący alerty (w GitHubie działają) |
| **Listy zadań** | `- [ ] zadanie` | Zależnie od wersji renderera; w GitHubie działają |
| **Definicje (listy definicji)** | `Termin` + `: definicja` | Nie jest standardowym Markdownem |
| **Spis treści `[TOC]`** | `[TOC]` | Nie działa w notebookach: użyj Outline lub wygeneruj spis kodem (zob. 6.14) |
| **Wyrównanie obrazów, kolory tekstu** | HTML + `style` | Zależnie od polityki bezpieczeństwa renderera |

Przykład diagramu Mermaid (jeśli masz odpowiednie rozszerzenie, narysuje się; jeśli nie, zobaczysz kod):

```mermaid
flowchart LR
    A[Dane surowe] --> B{Czyszczenie}
    B -->|OK| C[Analiza]
    B -->|Błędy| D[Raport jakości]
    C --> E[Wnioski]
```

### 6.14. Spis treści i nawigacja po notebooku

W notebooku **nie ma** automatycznego znacznika `[TOC]`. Masz trzy opcje:

1. **Outline** w VS Code (Explorer → Outline): zawsze aktualny, zero pracy.
2. **Ręczny spis** na górze notebooka z linkami do nagłówków (`[1. Dane](#1-dane)`; zob. 6.7, ⚠ działanie zależy od wersji).
3. **Spis generowany kodem** z pliku `.ipynb` (poniżej): uruchom komórkę, a wynik wklej do komórki Markdown na górze notebooka.

In [16]:
import json, re, os
from IPython.display import Markdown, display

# VS Code definiuje w kernelu zmienną __vsc_ipynb_file__ (ścieżka bieżącego notebooka); jeśli jej brak, ustaw ścieżkę ręcznie
nb_path = globals().get("__vsc_ipynb_file__", "przewodnik.ipynb")

if os.path.exists(nb_path):
    nb = json.load(open(nb_path, encoding="utf-8"))
    toc = []
    for cell in nb["cells"]:
        if cell["cell_type"] != "markdown":
            continue
        for line in "".join(cell["source"]).splitlines():
            m = re.match(r"^(#{1,3})\s+(.*)$", line)                        # nagłówki poziomów 1–3
            if m:
                level, title = len(m.group(1)), m.group(2).strip()
                slug = re.sub(r"[^\w\- ]", "", title.lower()).strip().replace(" ", "-")     # reguła kotwicy: małe litery, spacje → "-", bez interpunkcji
                toc.append(f"{'  ' * (level - 1)}- [{title}](#{slug})")
    toc_md = "\n".join(toc)
    print(toc_md[:800])                           # kod Markdown do wklejenia
    display(Markdown(toc_md[:800]))               # podgląd
else:
    print("Ustaw nb_path na ścieżkę swojego notebooka")

- [Jupyter Notebook w VS Code: skróty klawiaturowe, praca z komórkami i formatowanie Markdown](#jupyter-notebook-w-vs-code-skróty-klawiaturowe-praca-z-komórkami-i-formatowanie-markdown)
  - [1. Tryby pracy i uruchamianie komórek](#1-tryby-pracy-i-uruchamianie-komórek)
    - [1.1. Uruchamianie komórek](#11-uruchamianie-komórek)
  - [2. Skróty klawiaturowe](#2-skróty-klawiaturowe)
    - [2.1. Tryb poleceń (komórka zaznaczona, kursor poza edytorem)](#21-tryb-poleceń-komórka-zaznaczona-kursor-poza-edytorem)
    - [2.2. Tryb edycji (kursor w komórce)](#22-tryb-edycji-kursor-w-komórce)
    - [2.3. Wyszukiwanie w notebooku](#23-wyszukiwanie-w-notebooku)
    - [2.4. Nawigacja i okna](#24-nawigacja-i-okna)
    - [2.5. Okno Interactive (`.py` z komórkami `# %%`)](#25-okno-interactive-py-z-komórkami)

- [Jupyter Notebook w VS Code: skróty klawiaturowe, praca z komórkami i formatowanie Markdown](#jupyter-notebook-w-vs-code-skróty-klawiaturowe-praca-z-komórkami-i-formatowanie-markdown)
  - [1. Tryby pracy i uruchamianie komórek](#1-tryby-pracy-i-uruchamianie-komórek)
    - [1.1. Uruchamianie komórek](#11-uruchamianie-komórek)
  - [2. Skróty klawiaturowe](#2-skróty-klawiaturowe)
    - [2.1. Tryb poleceń (komórka zaznaczona, kursor poza edytorem)](#21-tryb-poleceń-komórka-zaznaczona-kursor-poza-edytorem)
    - [2.2. Tryb edycji (kursor w komórce)](#22-tryb-edycji-kursor-w-komórce)
    - [2.3. Wyszukiwanie w notebooku](#23-wyszukiwanie-w-notebooku)
    - [2.4. Nawigacja i okna](#24-nawigacja-i-okna)
    - [2.5. Okno Interactive (`.py` z komórkami `# %%`)](#25-okno-interactive-py-z-komórkami)

### 6.15. Wstawianie obrazów i pliki, komórki „Raw”

- **Komórka Raw** (typ „Raw” / `Ctrl+K M` → *Raw*): tekst nieprzetwarzany ani przez Markdown, ani Pythona; używany przy konwersji (`nbconvert`) do innych formatów. W codziennej pracy rzadko potrzebna.
- **Komórki Markdown w pliku `.py`**: linie `# %% [markdown]` a poniżej tekst w komentarzach `# ...` (zob. 2.5).
- **Przeciągnij i upuść**: plik obrazu na komórkę Markdown (dodaje załącznik `attachment:`) ⚠.
- **Zasada nazewnictwa plików**: bez spacji i polskich znaków w nazwach plików i katalogów obrazów (`img/wykres_sprzedazy.png`), aby uniknąć kłopotów z linkami.

---

## 7. Markdown generowany z kodu

Wynik analizy możesz wstawiać do raportu **dynamicznie**: tekst, tabele, wzory i HTML tworzone z wartości zmiennych (świetne do raportów, które odświeżają się po ponownym uruchomieniu).

| Obiekt `IPython.display` | Do czego |
|---|---|
| `Markdown(tekst)` | Renderuje tekst jak komórkę Markdown (nagłówki, tabele, listy, wzory) |
| `Math(latex)`, `Latex(tekst)` | Wzory LaTeX (`Math`: sam wzór; `Latex`: tekst z `$...$`) |
| `HTML(kod)` | Dowolny HTML (kolory, układy, ramki, tabele) |
| `Image(plik/URL, width=)`, `SVG`, `IFrame`, `Audio`, `Video` | Media |
| `display(a, b, c)` | Kilka wyników z jednej komórki (zamiast tylko ostatniego wyrażenia) |
| `clear_output(wait=True)` | Czyści wyniki (np. do odświeżania) |

In [17]:
import numpy as np, pandas as pd
from IPython.display import Markdown, Math, Latex, HTML, display

rng = np.random.default_rng(0)
df = pd.DataFrame({"region": ["Północ", "Południe", "Wschód"], "przychod": rng.integers(80, 200, 3), "marza": [0.18, 0.22, 0.15]})

total = df["przychod"].sum()
best = df.loc[df["przychod"].idxmax(), "region"]

# 1) tekst dynamiczny z f-string (Markdown)
display(Markdown(f"""
### Podsumowanie

- Łączny przychód: **{total:,} tys. PLN**
- Najlepszy region: **{best}**
- Średnia marża: **{df['marza'].mean():.1%}**
"""))

### Podsumowanie

- Łączny przychód: **479 tys. PLN**
- Najlepszy region: **Północ**
- Średnia marża: **18.3%**

In [18]:
# 2) tabela z DataFrame jako Markdown (wymaga pakietu tabulate: pip install tabulate)
display(Markdown(df.to_markdown(index=False, floatfmt=".2f")))

# 3) wzór z wartościami
mean, std = 52.4, 7.1
display(Math(rf"z = \frac{{x - {mean}}}{{{std}}}"))            # rf"": raw + f-string (podwójne {{ }} dla klamr LaTeX)
display(Latex(r"Odchylenie standardowe $\sigma = 7{,}1$ i średnia $\mu = 52{,}4$."))

| region   |   przychod |   marza |
|:---------|-----------:|--------:|
| Północ   |        182 |    0.18 |
| Południe |        156 |    0.22 |
| Wschód   |        141 |    0.15 |

In [19]:
# 4) HTML: kolorowa ramka (działa w wynikach komórek kodu, gdzie HTML jest renderowany)
display(HTML("""
<div style="border-left:4px solid #1f77b4; background:#eef5fb; padding:8px 12px; border-radius:4px">
  <b>Wniosek:</b> region <b>Południe</b> ma najwyższą marżę (22%), ale najniższy wolumen sprzedaży.
</div>
"""))

# 5) stylowanie DataFrame (formatowanie warunkowe, gradient); wymaga jinja2 (instalowany z pandas[...]; w razie braku: pip install jinja2)
try:
    styled = (df.style.format({"marza": "{:.0%}"}).background_gradient(subset=["przychod"], cmap="Blues").hide(axis="index"))
    display(styled)
except ImportError as e:
    print("Brak jinja2:", e)

ImportError: Pandas requires version '3.9.3' or newer of 'matplotlib' (version '3.9.2' currently installed).

In [20]:
# 6) kilka wyników z jednej komórki; pasek postępu w notebooku
from IPython.display import display
from tqdm.auto import tqdm
import time

display(df.head(2), df.describe())               # oba wyniki widoczne

for _ in tqdm(range(5), desc="Przetwarzanie"):   # tqdm.auto wybiera pasek dla notebooka
    time.sleep(0.05)

     region  przychod  marza
0    Północ       182   0.18
1  Południe       156   0.22

       przychod  marza
count      3.00   3.00
mean     159.67   0.18
std       20.74   0.04
min      141.00   0.15
25%      148.50   0.16
50%      156.00   0.18
75%      169.00   0.20
max      182.00   0.22

Przetwarzanie:   0%|          | 0/5 [00:00<?, ?it/s]

---

## 8. Struktura dobrego notebooka i dobre praktyki

### 8.1. Szablon (skopiuj do nowego notebooka)

Komórka Markdown na górze (tytuł + metadane), potem logiczne sekcje. Poniżej wzorzec w postaci gotowej do wklejenia:

````markdown
# Analiza sprzedaży 2025: nazwa projektu

| | |
|---|---|
| **Cel** | Co chcemy ustalić / jaką decyzję wesprzeć |
| **Dane** | Źródło, zakres dat, wersja/data pobrania |
| **Autor / data** | Imię, 2026-10-05 |
| **Środowisko** | Python 3.12, pandas 3.x, polars 1.x (`requirements.txt`) |

## Spis treści
(Outline w VS Code lub wygenerowany)

## 1. Konfiguracja i importy
## 2. Wczytanie danych
## 3. Kontrola jakości danych
## 4. Analiza eksploracyjna (EDA)
## 5. Modelowanie / testy
## 6. Wnioski i rekomendacje
## 7. Dalsze kroki
````

### 8.2. Dobre praktyki

| Obszar | Zasada | Dlaczego |
|---|---|---|
| Struktura | Jeden `#` (tytuł), sekcje `##`, podsekcje `###`; przed każdą dużą sekcją krótki opis „co i po co” | Outline, zwijanie, Run Cells in Section, czytelność dla innych |
| Komórki | Jedna myśl = jedna komórka; krótkie komórki; importy na górze | Łatwiejsze debugowanie i ponowne uruchamianie |
| Kolejność | Notebook musi działać od góry do dołu po **Restart → Run All** | Stan ukryty (zmienne z usuniętych/przesuniętych komórek) to główne źródło błędów |
| Powtarzalność | `rng = np.random.default_rng(42)`, zapis wersji bibliotek, ścieżki względne (`Path("data")`) | Odtwarzalne wyniki, działa na innym komputerze |
| Wyniki | Czyść wyniki przed commitem (**Clear All Outputs**) lub użyj `nbstripout` | Małe różnice w Git, brak wycieków danych |
| Dane wrażliwe | Nie zostawiaj haseł/tokenów w komórkach (użyj `.env` + `os.getenv`) i nie commituj danych klientów | Wyniki i kod zostają w pliku `.ipynb` |
| Długie obliczenia | Zapisuj wyniki pośrednie do plików (`parquet`/`pickle`) zamiast liczyć w kółko | Oszczędność czasu |
| Kod do ponownego użycia | Przenoś funkcje do modułu `.py` + `%autoreload 2` | Notebook jest do analizy/narracji, a nie do biblioteki kodu |
| Wizualizacje | Tytuł, podpisane osie, jednostki; wniosek w komórce Markdown pod wykresem | Wykres bez komentarza nie jest wnioskiem |
| Duże pliki | Unikaj zapisywania ogromnych wyników (`df` z milionami wierszy) w `.ipynb`; `df.head()`, agregaty | Mały, szybki w otwarciu plik |
| Wersjonowanie | Rozważ `jupytext` (parowanie `.ipynb` ↔ `.py`) lub okno Interactive z `# %%` | Czytelne diffy i code review |
| Narracja | Po każdym kluczowym kroku krótki komentarz: co zrobiono, co widać, co z tego wynika | Notebook jest dokumentem, nie tylko skryptem |

### 8.3. Typowe problemy w VS Code i szybkie rozwiązania

| Problem | Rozwiązanie |
|---|---|
| Brak kernela / „Kernel not found” | `Python: Select Interpreter` → wybierz środowisko z `ipykernel` (`pip install ipykernel`) → *Select Kernel* |
| Komórka „wisi” | Przycisk **Interrupt**; jeśli nie pomaga, **Restart** (traci zmienne) |
| Zmiany w module `.py` nie widać | `%load_ext autoreload` + `%autoreload 2` lub restart kernela |
| Duże wyniki zacinają edytor | `notebook.output.textLineLimit`, zwiń wyniki (`Ctrl+K T`), czyść wyniki |
| Skrót nie działa | Sprawdź tryb (poleceń vs edycji), fokus (wynik vs komórka) i konflikty w *Keyboard Shortcuts* (kolumna *When*) |
| Pakiet zainstalowany, ale `ImportError` | Instalacja poszła do innego środowiska: użyj `%pip install pakiet` w komórce (instaluje w kernelu) i zrestartuj kernel |
| Wykresy nie wyświetlają się | `%matplotlib inline` lub `plt.show()`; sprawdź czy notebook jest w zaufanym obszarze roboczym (Workspace Trust) |
| Notebook się nie otwiera / dziwne błędy rozszerzenia | Zaktualizuj rozszerzenia **Jupyter** i **Python**, **Developer: Reload Window** |
| Różnice w Git są ogromne | Czyść wyniki, użyj notebook diff (edytor różnic), `nbstripout` |

---

## 9. Ściągawki

### 9.1. Dwadzieścia najważniejszych skrótów (Windows/Linux)

| # | Skrót | Działanie |
|---|---|---|
| 1 | `Shift+Enter` | Uruchom komórkę i przejdź do następnej |
| 2 | `Ctrl+Enter` | Uruchom komórkę i zostań |
| 3 | `Alt+Enter` | Uruchom i wstaw nową komórkę poniżej |
| 4 | `Esc` / `Enter` | Tryb poleceń / tryb edycji |
| 5 | `A` / `B` | Wstaw komórkę nad / pod |
| 6 | `M` / `Y` | Komórka Markdown / kod |
| 7 | `D D` | Usuń komórkę |
| 8 | `Z` | Cofnij (także usunięcie komórki) |
| 9 | `J` / `K` | Zaznacz następną / poprzednią komórkę |
| 10 | `Alt+↑` / `Alt+↓` | Przesuń komórkę |
| 11 | `Shift+Alt+↑` / `↓` | Skopiuj komórkę |
| 12 | `Ctrl+K Ctrl+Shift+\` | Podziel komórkę w miejscu kursora |
| 13 | `L` / `Shift+L` | Numery linii: komórka / cały notebook |
| 14 | `←` / `→` | Zwiń / rozwiń sekcję pod nagłówkiem (tryb poleceń) |
| 15 | `Ctrl+K T` | Zwiń/rozwiń wynik komórki |
| 16 | `Alt+Delete` | Wyczyść wynik komórki |
| 17 | `Ctrl+F` | Szukaj w notebooku (lejek: wybór zakresu) |
| 18 | `Ctrl+Shift+P` | Paleta poleceń |
| 19 | `Ctrl+Space` | Podpowiedzi IntelliSense |
| 20 | `Ctrl+K Ctrl+S` | Edytor skrótów klawiaturowych |

### 9.2. Ściągawka Markdown

| Efekt | Składnia |
|---|---|
| Nagłówki | `# H1` … `###### H6` |
| **Pogrubienie**, *kursywa*, ~~przekreślenie~~ | `**tekst**`, `*tekst*`, `~~tekst~~` |
| `Kod w linii` | `` `kod` `` |
| Blok kodu | ```` ```python ```` … ```` ``` ```` |
| Lista punktowana / numerowana | `- element`, `1. element` |
| Zagnieżdżenie | wcięcie 2–4 spacji |
| Cytat | `> tekst` |
| Link | `[tekst](url)` |
| Obraz | `![alt](ścieżka)` lub `<img src="..." width="400">` |
| Tabela | `\| a \| b \|` + `\|---\|---\|` |
| Linia pozioma | `---` |
| Złamanie linii | dwie spacje, `\` lub `<br>` |
| Wzór w linii / blok | `$E=mc^2$` / `$$ ... $$` |
| Klawisz | `<kbd>Ctrl</kbd>` |
| Sekcja zwijana | `<details><summary>…</summary>…</details>` |
| Komentarz | `<!-- komentarz -->` |
| Ucieczka znaku | `\*`, `\#`, `` \` `` |
| Dynamiczny Markdown z kodu | `display(Markdown(f"…"))` |

### 9.3. Gdzie szukać dalej

- Oficjalna dokumentacja: *Jupyter Notebooks in VS Code* (code.visualstudio.com/docs/datascience/jupyter-notebooks), *Python Interactive*, *Data Wrangler*, *Manage Jupyter Kernels*.
- Domyślne skróty w Twojej wersji: **Keyboard Shortcuts** → filtr `notebook`, opcja *Show Default Keybindings* (JSON).
- Specyfikacje: CommonMark, GFM (tabele, przekreślenia, listy zadań), KaTeX (obsługiwane polecenia: wyszukaj „KaTeX supported functions”).